# Generated by Django 3.0.3 on 2020-05-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('salary', models.PositiveIntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('tell', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss.Boss')),
            ],
        ),
    ]
