# Generated by Django 3.0.3 on 2020-05-21 09:39

from django.db import migrations, models
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commodity',
            name='img',
            field=models.ImageField(default='uploads\\product-1.jpg', upload_to=shop.models.get_image_path),
        ),
        migrations.AddField(
            model_name='commodity',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
