# Generated by Django 3.0.3 on 2020-05-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200522_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='created_date',
        ),
    ]
