# Generated by Django 3.0.3 on 2020-05-22 04:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_commodity_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='img',
            field=models.ImageField(default='uploads\\product-1.jpg', null=True, upload_to=shop.models.get_image_path),
        ),
    ]
