# Generated by Django 3.0.3 on 2020-05-22 04:21

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200522_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='img',
            field=models.ImageField(blank=True, default='uploads\\product-1.jpg', null=True, upload_to=shop.models.get_image_path),
        ),
    ]
