# Generated by Django 3.0.3 on 2020-05-23 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='gian',
        ),
        migrations.AddField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 12, 43, 52, 661937, tzinfo=utc)),
        ),
    ]
