# Generated by Django 3.0.3 on 2020-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gian', models.PositiveIntegerField()),
                ('tell', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
